/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.contas.exercicio_02.windows;

import br.com.contas.exercicio_02.classes.ContaBancaria;
import br.com.contas.exercicio_02.classes.ContaCorrente;
import br.com.contas.exercicio_02.classes.ContaPoupanca;
import br.com.contas.exercicio_02.classes.OperacoesBancarias;
import java.awt.BorderLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author thiago
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        MnPoupanca = new javax.swing.JMenuItem();
        MnContaCorrente = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistemas de contas Bancarias");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });

        jLabel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jLabel1AncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jLabel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jLabel1ComponentResized(evt);
            }
        });

        jMenu1.setText("Cadastro");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItem1.setText("Contas Bancárias");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        MnPoupanca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        MnPoupanca.setText("Contas Poupança");
        MnPoupanca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnPoupancaActionPerformed(evt);
            }
        });
        jMenu1.add(MnPoupanca);

        MnContaCorrente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        MnContaCorrente.setText("Conta Corrente");
        MnContaCorrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnContaCorrenteActionPerformed(evt);
            }
        });
        jMenu1.add(MnContaCorrente);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Operações");

        jMenuItem2.setText("Creditar na Conta Poupança");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem5.setText("Creditar Em Poupança");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Debitar da Conta Poupança");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Debitar da Poupança");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);
        jMenu2.add(jSeparator1);

        jMenuItem8.setText("Creditar na Conta Corrente");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuItem4.setText("Debitar ContaCorrente");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem3.setText("Tranferência entre Contas correntes");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        ContaBancariaGUI gui = new ContaBancariaGUI();
        gui.setContaBancaria(contaBancaria);
        gui.setModal(true);
        gui.setVisible(true);

        contaBancaria = gui.getContaBancaria();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void MnPoupancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnPoupancaActionPerformed
        ContaPoupancaGUI guiP = new ContaPoupancaGUI();
        guiP.setContaPoupanca(contaPoupanca);
        guiP.setModal(true);
        guiP.setVisible(true);

        contaPoupanca = guiP.getContaPoupanca();

    }//GEN-LAST:event_MnPoupancaActionPerformed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowStateChanged

    private void MnContaCorrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnContaCorrenteActionPerformed
        ContaCorrenteGUI guicc = new ContaCorrenteGUI();

        guicc.setContaCorrente(contaCorrente);
        guicc.setModal(true);
        guicc.setVisible(true);
        contaCorrente = guicc.getContaCorrente();

    }//GEN-LAST:event_MnContaCorrenteActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        if (isContaPoupancaPreenchida()) {
            String valorCreditadoPoupanca = JOptionPane.showInputDialog(this, "Titular da conta: " + contaPoupanca.getNome()
                    + "\nSaldo atual: R$ " + contaPoupanca.getSaldo()
                    + "\nDigite o valor", "Poupança | Creditar saldo", JOptionPane.QUESTION_MESSAGE);

            if (valorCreditadoPoupanca != null) {
                double valorCreditadoPoupancaValor = Double.parseDouble(valorCreditadoPoupanca);
                operacoesBancarias.creditarContaPoupanca(contaPoupanca, valorCreditadoPoupancaValor);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Preencha os dados da conta poupança");
        }

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        if (isContaPoupancaPreenchida()) {
            String valorCreditadoPoupanca = JOptionPane.showInputDialog(this, "Titular da conta: " + contaPoupanca.getNome()
                    + "\n\nSaldo na conta Bancaria: R$ " + contaPoupanca.getSaldo()
                    + "\nSaldo atual: R$ " + contaPoupanca.getSaldoPoupanca()
                    + "\nDigite o valor", "Poupança | Creditar em poupança", JOptionPane.QUESTION_MESSAGE);

            if (valorCreditadoPoupanca != null) {
                double valorCreditadoPoupancaValor = Double.parseDouble(valorCreditadoPoupanca);
                operacoesBancarias.creditarEmPoupanca(contaPoupanca, valorCreditadoPoupancaValor);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Preencha os dados da conta poupança");
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        if (isContaPoupancaPreenchida()) {
            String valorCreditadoPoupanca = JOptionPane.showInputDialog(this, "Titular da conta: " + contaPoupanca.getNome()
                    + "\nSaldo atual: R$ " + contaPoupanca.getSaldo()
                    + "\nDigite o valor", "Poupança | Creditar em poupança", JOptionPane.QUESTION_MESSAGE);

            if (valorCreditadoPoupanca != null) {
                double valorCreditadoPoupancaValor = Double.parseDouble(valorCreditadoPoupanca);
                operacoesBancarias.debitarContaPoupanca(contaPoupanca, valorCreditadoPoupancaValor);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Preencha os dados da conta poupança");
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        if (isContaPoupancaPreenchida()) {
            String valorCreditadoPoupanca = JOptionPane.showInputDialog(this, "Titular da conta: " + contaPoupanca.getNome()
                    + "\n\nSaldo na conta Bancaria: R$ " + contaPoupanca.getSaldo()
                    + "\nSaldo na poupança: R$ " + contaPoupanca.getSaldoPoupanca()
                    + "\n\nDigite o valor", "Poupança | Debitar da poupança", JOptionPane.QUESTION_MESSAGE);

            if (valorCreditadoPoupanca != null) {
                double valorCreditadoPoupancaValor = Double.parseDouble(valorCreditadoPoupanca);
                operacoesBancarias.debitarDaPoupanca(contaPoupanca, valorCreditadoPoupancaValor);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Preencha os dados da conta poupança");
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        if (isContaCorrentePreenchida()) {
            String valorDebitoContaCorrente = JOptionPane.showInputDialog(this, "Titular da conta: " + contaCorrente.getNome()
                    + "\nSaldo Disponivel: R$ " + contaCorrente.getSaldo() + "\n\nDigite o valor do saque", "Conta Corrente | Sacar", JOptionPane.QUESTION_MESSAGE);

            if (valorDebitoContaCorrente != null) {
                double valorDebitoConCorrente = Double.parseDouble(valorDebitoContaCorrente);
                operacoesBancarias.debitarContaCorrente(contaCorrente, valorDebitoConCorrente);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Preencha os dados da Conta Corrente");
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        if (isContaCorrentePreenchida()) {
            String valorDebitoContaCorrente = JOptionPane.showInputDialog(this, "Titular da conta: "
                    + contaCorrente.getNome() + "\nSaldo Disponivel: R$ " + contaCorrente.getSaldo() + "\n\nDigite o valor do depósito", "Conta Corrente | Depositar", JOptionPane.QUESTION_MESSAGE);

            if (valorDebitoContaCorrente != null) {
                double valorDebitoConCorrente = Double.parseDouble(valorDebitoContaCorrente);
                operacoesBancarias.creditarContaCorrente(contaCorrente, valorDebitoConCorrente);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Preencha os dados da Conta Corrente");
        }
            }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        if (isContaCorrentePreenchida()) {
            ContaCorrente contaDestino = new ContaCorrente();
            contaDestino.setNome("Renato");
            contaDestino.setSaldo(0);
            String valorDebitoContaCorrente = JOptionPane.showInputDialog(this, "Conta Origem: " + contaCorrente.getNome() + "\nConta Destino: " + contaDestino.getNome().toUpperCase()
                    + "\n\nSaldo Disponivel: R$ " + contaCorrente.getSaldo() + "\n\nDigite o valor do depósito", "Conta Corrente | Transferência", JOptionPane.QUESTION_MESSAGE);

            if (valorDebitoContaCorrente != null) {

                double valorDebitoConCorrente = Double.parseDouble(valorDebitoContaCorrente);
                operacoesBancarias.transferenciaBancaria(contaCorrente, contaDestino, valorDebitoConCorrente);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Preencha os dados da Conta Corrente");
        }

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jLabel1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel1ComponentResized


    }//GEN-LAST:event_jLabel1ComponentResized

    private void jLabel1AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel1AncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1AncestorMoved

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        atualizarImagemFundo();  // TODO add your handling code here:
    }//GEN-LAST:event_formComponentResized

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentHidden

    private void jLabel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel1AncestorAdded
        ImagemFundo();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    private ContaBancaria contaBancaria = null;
    private ContaPoupanca contaPoupanca = null;
    private ContaCorrente contaCorrente = null;
    private OperacoesBancarias operacoesBancarias = new OperacoesBancarias();
    private Image imagemFundo;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MnContaCorrente;
    private javax.swing.JMenuItem MnPoupanca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables

    private boolean isContaPoupancaPreenchida() {
        return contaPoupanca != null;
    }

    private boolean isContaCorrentePreenchida() {
        return contaCorrente != null;
    }

    public void ImagemFundo() {
        imagemFundo = new ImageIcon(getClass().getResource("../assets/imagens/contas-bancarias.jpg")).getImage();
        Image scaledInstance = imagemFundo.getScaledInstance(getWidth(), getHeight(), Image.SCALE_SMOOTH);

        jLabel1.setIcon(new ImageIcon(scaledInstance));
    }

    public void atualizarImagemFundo() {

    }
}
